GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/lk

###
POST http://localhost:3001/api/persons/ 
content-type: application/json

{
    "name": "estes",
    "number": "852147"
}
###
PUT http://localhost:3001/api/persons/660c7ea5625b6a8e20fd07ce


{
    "name": "ROCHIS",
    "number": 1122647161,

} 




###
DELETE http://localhost:3001/api/persons/660059bf0bcabeed4de8b2be


###













